name: Ender-Kwietie
favicon: null
layout_spectrum: 0.6710027386434376
typography_spectrum: 0.15803440497256815
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6869129033293575
  lightness: 0.8574293935671449
  saturation: 0.8614392543677241
  rhythmicContrast: 0.23966297530569136
purpose: []
